---
  - name: create ansible work directory
    local_action: file path={{ work_path }} state=directory mode=0755
    run_once: true

  - name: get conf from conf_center
    local_action: git repo={{ conf_repo }} dest={{ conf_path }} version={{ conf_hash | default('master') }}
    run_once: true

  - name: get remote conf
    remote_generate: types={{ type }}

  - name: get local conf
    local_action: local_generate groups={{ group_names }}  lists={{ inventory_file }} addr={{ PRIVATE_IP[0] }}

  - name: copy main conf file
    template: src={{ src_conf_path }}/conf/{{ item }} dest={{ dest_conf_path }}/conf/{{ item }}
    with_items:
      - less_server.json
      - less_server.key

  - name: copy nginx conf file
    template: src={{ src_conf_path }}/conf/{{ item }} dest={{ dest_conf_path }}/nginx/conf/{{ item }}
    with_items:
      - nginx.conf

  - name: copy supervisor.conf when edge
    template: src={{ src_conf_path }}/supervisor.d/{{ item }}.conf dest={{ supervisor_path }}/
    with_items:
      - less_server
      - less_billing
      - less_sender_edge
      - less_access
    when: type == "cdn"

  - name: copy supervisor.conf when origin
    template: src={{ src_conf_path }}/supervisor.d/{{ item }}.conf dest={{ supervisor_path }}/
    with_items:
      - less_server
      - less_publish
      - less_sender_origin
    when: type == "origin"

  - name: add less-hls to system service
    file: src={{ LESS_PATH }}/less-hls dest={{ LESS_PROXY }} state=link 
