---
  - name: create neccessary directory
    file: path={{ item }} state=directory mode=0755
    with_items:
        - "{{ log_path }}/less/hls"
        - "{{ backup_path }}/less-server"
        - "{{ dest_conf_path }}/conf"
        - "{{ dest_conf_path }}/nginx/conf"
