- include_vars: cdn/common/supervisor/vars/main.yml
  tags:
    - always

- import_tasks: cdn/common/tasks/init.yml
  tags:
    - init
    - install

- import_tasks: init.yml
  tags:
    - init
    - install

- import_tasks: cdn/common/tasks/backup.yml
  tags:
    - app
    - backup
    - config
    - update

- import_tasks: cdn/common/tasks/app.yml
  tags:
    - app
    - install
    - update

- import_tasks: backup.yml
  tags:
    - install

- import_tasks: config.yml
  tags:
    - install
    - config

- import_tasks: cdn/common/tasks/version.yml
  tags:
    - install
    - version
    - config
    - update

- import_tasks: restart.yml
  tags:
    - restart

- import_tasks: cdn/common/tasks/rollback.yml
  tags:
    - rollback
