# note: CDN 服务发布
# danger: 6
# type: cdn_release
# arg: role, select: $release.role
# arg: tags, type: list, select: $tag.tag, depend: role
# arg: version, select: $release, depend: role
---
- hosts: "{{ node }}"
  roles:
    - "cdn/{{ role }}"
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
