---
- name: download els package
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.3.rpm
    dest: "{{ work_path }}/elasticsearch-5.4.3.rpm"

- name: install els
  command: "rpm -ivh {{ work_path }}/elasticsearch-5.4.3.rpm"
