---
   - name: fetch core package
     fetch_pack: "project=mobydick version={{ version }} dest={{ work_path }} component=core cdn={{ fetch_from_cdn | default(true) }}"
     register: fetch_result
   - name: unarchive core package
     unarchive:
       src: "{{ work_path }}/{{ fetch_result.tar }}"
       dest: "{{ work_path }}"
       remote_src: yes
   - name: install core
     shell: "cd {{ work_path }}/mobydick && {{ luarocks_bin }} make mobydick-{{ fetch_result.core_version] }}-0.rockspec --force"
   - name: cleanup
     with_items:
       - "{{ work_path }}/{{ fetch_result.tar }}"
       - "{{ work_path }}/mobydick"
     file:
       path: "{{ item }}"
       state: absent

