---
  - name: create ansible work directory
    local_action: file path={{ work_path }} state=directory mode=0755
    run_once: true
  - name: update conf
    local_action: git repo={{ conf_repo }} dest={{ conf_path }} version={{ conf_hash | default('master') }}
    run_once: true
  - name: copy supervisor.conf
    copy: src={{ src_conf_path }}/supervisor.d/{{ project }}.conf dest={{ supervisor_path }}/
