---
  - name: fetch app package
    fetch_pack: "project={{ project }} version={{ version }} dest={{ work_path }} component=app cdn={{ fetch_from_cdn | default(true) }}"
    register: fetch_result
  - name: create directory
    with_items:
      - "{{ work_path }}/{{ fetch_result.tar |hash('md5') }}"
    file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
  - name: unarchive app package
    unarchive:
      src: "{{ work_path }}/{{ fetch_result.tar }}"
      dest: "{{ work_path }}/{{ fetch_result.tar |hash('md5') }}"
      remote_src: yes
  - name: sync html to disk
    command: "rsync -r --delete --force {{ work_path }}/{{ fetch_result.tar |hash('md5') }}/{{ project }}/nginx/html/ {{ main_path }}/nginx/html/"
  - name: sync html to shm
    command: "rsync -r --delete --force {{ work_path }}/{{ fetch_result.tar |hash('md5') }}/{{ project }}/nginx/html/ /dev/shm/html/"
  - name: chmod a+w /dev/shm/html 
    command: "chmod a+w /dev/shm/html"
