---
  - name: set facts
    set_fact: type={{ project }}
  - name: create ansible work directory
    local_action: file path={{ work_path }} state=directory mode=0755
    run_once: true
  - name: update conf
    local_action: git repo={{ conf_repo }} dest={{ conf_path }} version={{ conf_hash | default('master') }}
    run_once: true
  - name: create directory
    with_items:
      - "{{ dest_conf_path }}/conf/{{ project }}"
    file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
  - name: sync config
    synchronize: src={{ src_conf_path }}/conf/ dest={{ dest_conf_path }}/conf/ rsync_opts=["--exclude={{ project }}"]
  - name: sync config
    synchronize: src={{ src_conf_path }}/conf/{{ project }}/ dest={{ dest_conf_path }}/conf/{{ project }}/ delete=yes
  - name: sync template
    template: src={{ src_conf_path }}/{{ item }} dest={{ dest_conf_path }}/{{ item }}
    with_items:
      - "conf/{{ project }}/pk.conf"
