---
- name: create ansible work directory
  local_action: file path={{ work_path }} state=directory mode=0755
  run_once: true

- name: update conf
  local_action: git repo={{ conf_repo }} dest={{ conf_path }} version={{ conf_hash | default('master') }}
  run_once: true

- name: config updns
  template: "src={{ src_conf_path }}/{{ item }} dest={{ dest_conf_path }}/{{ item }}"
  with_items:
    - config.json

- name: sync supervisor config
  template: src={{ src_conf_path }}/supervisor.d/{{ item }} dest={{ supervisor_path }}/{{ item }}
  with_items:
    - "updns.conf"
