---
- name: add supervisor conf
  template: src={{ src_conf_path }}/supervisor.d/{{ item }} dest={{ supervisor_path }}/{{ item }}
  with_items:
    - heka.conf

- name: restart heka
  supervisorctl: name=heka state=restarted
