---
- name: fetch app package
  fetch_pack: "project={{ role }} version={{ version }} dest={{ work_path }} component=app cdn={{ fetch_from_cdn | default(true) }}"
  register: fetch_result
- name: unarchive app package
  unarchive:
    src: "{{ work_path }}/{{ fetch_result.tar }}"
    dest: "{{ prefix_path }}"
    remote_src: yes

