---
- name: app init before unarchive
  shell: |
      if [ -f /usr/local/bepo/bc/bin/bearcache ]
      then
        mv /usr/local/bepo/bc/bin/bearcache /usr/local/bepo/bc/bin/bearcache.old
      fi

- name: fetch core package
  fetch_pack: "project={{ project }} version={{ version }} dest={{ work_path }} component=core cdn={{ fetch_from_cdn | default(true) }}"
  register: fetch_result

- name: unarchive core package
  unarchive:
    src: "{{ work_path }}/{{ fetch_result.tar }}"
    dest: "{{ prefix_path }}"
    remote_src: yes
