---
- name: create ansible work directory
  local_action: file path={{ work_path }} state=directory mode=0755
  run_once: true

- name: update conf
  local_action: git repo={{ conf_repo }} dest={{ conf_path }} version={{ conf_hash | default('master') }}
  run_once: true

- name: collect facts
  fetch_meta: project={{ project }}

- name: sync stunnel config template
  template: src={{ src_conf_path }}/stunnel.conf dest={{ dest_conf_path }}/etc/stunnel/stunnel.conf

- name: sync stunnel supervisor template
  template: src={{ src_conf_path }}/supervisor.d/stunnel.conf dest={{ supervisor_path }}/stunnel.conf
