---
  - name: create ansible work directory
    local_action: file path={{ work_path }} state=directory mode=0755
    run_once: true
  - name: update conf
    local_action: git repo={{ conf_repo }} dest={{ conf_path }} version={{ conf_hash | default('master') }}
    run_once: true
  - name: create conf directory
    with_items:
      - "{{ dest_conf_path }}/conf/quic_proxy/"
      - "{{ dest_conf_path }}/app/etc/"
    file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
  - name: sync config
    synchronize: src={{ src_conf_path }}/conf/ dest={{ dest_conf_path }}/conf/ rsync_opts="--exclude=quic_proxy"
  - name: sync config
    synchronize: src={{ src_conf_path }}/conf/quic_proxy/ dest={{ dest_conf_path }}/conf/quic_proxy/ delete=yes
  - name: sync template
    template: src={{ src_conf_path }}/{{ item }} dest={{ dest_conf_path }}/{{ item }}
    with_items:
      - "app/etc/config.lua"
      - "conf/nginx.conf"
  - name: sync template
    template: src={{ src_conf_path }}/{{ item }} dest={{ dest_conf_path }}/{{ item }}
    with_items:
      - conf/quic_proxy/main.conf
      - conf/quic_proxy/quic.conf
      - conf/quic_proxy/upstream.conf
