---
- name: check redis data path
  file: "path={{ item }} state=directory mode=0755"
  with_items:
    - "{{ redis_rdb_path }}"
    - "{{ dest_conf_path }}/etc"

- name: create ansible work directory
  local_action: file path={{ work_path }} state=directory mode=0755
  run_once: true

- name: update conf
  local_action: git repo={{ conf_repo }} dest={{ conf_path }} version={{ conf_hash | default('master') }}
  run_once: true

- name: set facts
  fetch_meta: project={{ project }}
