---
- name: delete log_io
  lineinfile:
      dest: "{{ crond_path }}"
      state: absent
      regexp: 'log_io'

- name: add crond task
  lineinfile:
      dest: "{{ crond_path }}"
      state: present
      line: '* * * * * root ({{ main_path }}/logcut)'
