#note: CACHE_PEER配置
##danger: 8

- name: get inventory list
  local_action: git repo=ssh://git@gitlab.s.upyun.com:18022/infrastructure/inventory.git dest=/tmp/ansible_init
  run_once: true

- name: get network type
  shell: cat /etc/upyun.cfg | grep NETWORK | awk -F "=" '{print $2}'
  register: net_result

- name: make peer file
  local_action: script get_v406_ip.sh "{{ net_result.stdout }}"
  register: peer_result

- name: modify CACHE_PEER when CTN
  replace:
    dest: /etc/upyun.cfg
    regexp: '^(CACHE_PEER=\").*'
    replace: '\1.#{{ peer_result.stdout_lines[0] }}"'
  when: net_result.stdout == "CTC"

- name: modify CACHE_PEER when CUN
  replace:
    dest: /etc/upyun.cfg
    regexp: '^(CACHE_PEER=\").*'
    replace: '\1.#{{ peer_result.stdout_lines[0] }}"'
  when: net_result.stdout == "CNC"

- name: modify CACHE_PEER when CMN
  replace:
    dest: /etc/upyun.cfg
    regexp: '^(CACHE_PEER=\").*'
    replace: '\1.#{{ peer_result.stdout_lines[0] }}"'
  when: net_result.stdout == "CMC"

- name: modify CACHE_PEER when ORG
  replace:
    dest: /etc/upyun.cfg
    regexp: '^(CACHE_PEER=\").*'
    replace: '\1.#{{ peer_result.stdout_lines[0] }}"'
  when: net_result.stdout == "ORG"

- name: modify CACHE_PEER when SCND
  replace:
    dest: /etc/upyun.cfg
    regexp: '^(CACHE_PEER=\").*'
    replace: '\1.#{{ peer_result.stdout_lines[0] }}"'
  when: net_result.stdout == "SCND"

- name: modify CACHE_PEER when SCNR
  replace:
    dest: /etc/upyun.cfg
    regexp: '^(CACHE_PEER=\").*'
    replace: '\1.#{{ peer_result.stdout_lines[0] }}"'
  when: net_result.stdout == "SCNR"

- name: modify CACHE_PEER when ABROAD
  replace:
    dest: /etc/upyun.cfg
    regexp: '^(CACHE_PEER=\").*'
    replace: '\1.#{{ peer_result.stdout_lines[0] }}"'
  when: net_result.stdout == "ABROAD"
