---
  - name: remove .kong_env
    file:
      state: absent
      path: "{{ main_path }}/.kong_env"
  - name: prepare kong
    command: "{{ main_path }}/bin/kong prepare -p {{ main_path }} -c {{ main_path }}/kong.conf --nginx-conf {{ main_path }}/nginx.conf.template"