prefix_path: "/opt"
main_path: "{{ prefix_path }}/elasticsearch-6.8.1"
conf_path: "{{ main_path }}/config"
supervisor_path: "/etc/supervisor.d"

app_tgz: "roles/{{ project }}/files/elasticsearch-6.8.1.tar.gz"
