---
- include_vars: cdn/common/supervisor/vars/main.yml
  tags:
     - always
- include_tasks: cdn/common/tasks/init.yml
  tags:
     - init
     - install
- include_tasks: init.yml
  tags:
     - init
     - install
- include_tasks: cdn/common/tasks/backup.yml
  tags:
     - backup
     - config
     - app
- include_tasks: cdn/common/tasks/app.yml
  tags:
     - install
     - app
- include_tasks: config.yml
  tags:
     - config
     - install
- include_tasks: cdn/common/tasks/version.yml
  tags:
     - app
     - config
     - install
     - version
- include_tasks: clear.yml
  tags:
     - clear
- include_tasks: reload.yml
  tags:
     - reload
- include_tasks: cdn/common/tasks/rollback.yml
  tags:
     - rollback
